[tool.bumpversion]
current_version = "0.0.2"
parse = """(?x)
    (?P<major>0|[1-9]\\d*)\\.
    (?P<minor>0|[1-9]\\d*)\\.
    (?P<patch>0|[1-9]\\d*)
"""

serialize = [
    "{major}.{minor}.{patch}"
]
search = "{current_version}"
replace = "{new_version}"
regex = false
ignore_missing_version = false
ignore_missing_files = false
tag = true
sign_tags = false
tag_name = "v{new_version}"
tag_message = "Bump version: {current_version} → {new_version}"
allow_dirty = false
commit = true
message = "Bump version: {current_version} → {new_version}"

[[tool.bumpversion.files]]
filename = "subworkflows/grid_search/main.nf"
search = "pipeline_version = \"{current_version}\""
replace = "pipeline_version = \"{new_version}\""

[[tool.bumpversion.files]]
filename = "subworkflows/normal/main.nf"
search = "pipeline_version = \"{current_version}\""
replace = "pipeline_version = \"{new_version}\""

[[tool.bumpversion.files]]
filename = "subworkflows/other/main.nf"
search = "pipeline_version = \"{current_version}\""
replace = "pipeline_version = \"{new_version}\""

[[tool.bumpversion.files]]
filename = "main.nf"
search = "pipeline_version = \"{current_version}\""
replace = "pipeline_version = \"{new_version}\""
